// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _2024._05._02面試題目.Models.EFModels;

public partial class Account
{
    public string AccountGuid { get; set; }

    public string OwnerGuid { get; set; }

    public int BranchId { get; set; }

    public int AcctSerialId { get; set; }

    public string AccountKind { get; set; }

    public string AccountName { get; set; }

    public string AccountStatus { get; set; }

    public string CacheTime { get; set; }

    public virtual NetBankUser Owner { get; set; }
}