// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace _2024._05._02面試題目.Models.EFModels;

public partial class NetBankUser
{
    public string UserGuid { get; set; }

    public string NationalId { get; set; }

    public int UserKind { get; set; }

    public string UserName { get; set; }

    public string Status { get; set; }

    public string ApplyDate { get; set; }

    public string CacheTime { get; set; }

    public string UpdatePasswordDate { get; set; }

    public bool IsAlive { get; set; }

    public string SyncAccount { get; set; }

    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}